namespace SpreadingJoy.Domain.EntityModels;

// One image, already fetched and stored by us.
//
// The bytes are ours, not a hotlink. A URL that resolved to a cat drawing when
// the customer pasted it can resolve to anything at all by the time the job
// reaches the press, and the press is where that stops being recoverable.
// SourceUrl is kept for provenance — it's evidence for a takedown dispute, not
// something the application ever fetches again.
public partial class Artwork
{
    public int ArtworkId { get; set; }

    // Null for artwork a guest attached before any customer record existed.
    public int? CustomerId { get; set; }

    // Where it came from, if it came from the internet. Null for uploads.
    public string? SourceUrl { get; set; }

    // What the customer called it, if they uploaded it. Display only — never
    // used to build a path.
    public string? OriginalFileName { get; set; }

    // Our name for it on disk: "{sha256}.{ext}", generated by us, so a hostile
    // filename can't walk out of the artwork directory.
    public string StoredFileName { get; set; } = null!;

    public string ContentType { get; set; } = null!;

    public long ByteSize { get; set; }

    public int WidthPx { get; set; }

    public int HeightPx { get; set; }

    // Lowercase hex SHA-256 of the stored bytes. Two customers pasting the same
    // URL share one row, and it's how a rejected image is recognised if someone
    // submits it again under a different link.
    public string Sha256 { get; set; } = null!;

    public string Status { get; set; } = ArtworkStatus.Pending;

    public string? RejectionReason { get; set; }

    public int? ReviewedByUserId { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Customer? Customer { get; set; }

    public virtual User? ReviewedByUser { get; set; }
}

// Where an image sits in its review queue. Nothing prints until a human has
// looked at it, which is the whole point of the queue existing.
public static class ArtworkStatus
{
    public const string Pending = "Pending";
    public const string Approved = "Approved";
    public const string Rejected = "Rejected";

    public static readonly string[] All = [Pending, Approved, Rejected];
}
