using SpreadingJoy.Domain.Artworks;

namespace SpreadingJoy.DAL.Imaging;

// Keeps artwork in a folder on disk.
//
// The folder is deliberately outside wwwroot. Static files there are served by
// the framework with no code in the way, which would mean every image was
// publicly readable by anyone who guessed a URL — including the ones a
// moderator rejected. Serving them through a controller costs a little
// throughput and buys the ability to say no.
public class FileSystemImageStore : IImageStore
{
    private readonly string _rootPath;
    private readonly string _publicPathPrefix;

    public FileSystemImageStore(string rootPath, string publicPathPrefix = "/artwork/file")
    {
        _rootPath = rootPath;
        _publicPathPrefix = publicPathPrefix.TrimEnd('/');

        Directory.CreateDirectory(_rootPath);
    }

    public async Task<string> SaveAsync(byte[] content, string extension, string sha256, CancellationToken cancellationToken = default)
    {
        // The name is built entirely from a hash we computed and an extension
        // from the decoder. Nothing the customer supplied reaches it — a
        // filename taken from a URL is how "../../appsettings.json" gets
        // written over.
        var fileName = $"{sha256}.{extension.TrimStart('.')}";
        var fullPath = Path.Combine(_rootPath, fileName);

        // Content-addressed, so the same bytes always land on the same path.
        // If it's already there it's byte-identical and rewriting it is waste.
        if (!File.Exists(fullPath))
            await File.WriteAllBytesAsync(fullPath, content, cancellationToken);

        return fileName;
    }

    public async Task<byte[]?> ReadAsync(string storedFileName, CancellationToken cancellationToken = default)
    {
        var fullPath = ResolveWithinRoot(storedFileName);
        if (fullPath == null || !File.Exists(fullPath))
            return null;

        return await File.ReadAllBytesAsync(fullPath, cancellationToken);
    }

    public Task DeleteAsync(string storedFileName, CancellationToken cancellationToken = default)
    {
        var fullPath = ResolveWithinRoot(storedFileName);

        if (fullPath != null && File.Exists(fullPath))
            File.Delete(fullPath);

        return Task.CompletedTask;
    }

    public string PublicPath(string storedFileName) => $"{_publicPathPrefix}/{storedFileName}";

    // Belt and braces. Names in the database were generated by SaveAsync and
    // are safe by construction — but this method's input is a string that
    // travelled through a URL and a database, and the cost of being wrong is
    // reading an arbitrary file off the server. Resolve it and confirm it
    // actually landed inside the root.
    private string? ResolveWithinRoot(string storedFileName)
    {
        if (string.IsNullOrWhiteSpace(storedFileName))
            return null;

        // Reject anything with structure before resolving: a bare filename is
        // the only legitimate input.
        if (storedFileName.Contains('/') || storedFileName.Contains('\\') || storedFileName.Contains(".."))
            return null;

        var root = Path.GetFullPath(_rootPath);
        var candidate = Path.GetFullPath(Path.Combine(root, storedFileName));

        var rootWithSeparator = root.EndsWith(Path.DirectorySeparatorChar)
            ? root
            : root + Path.DirectorySeparatorChar;

        return candidate.StartsWith(rootWithSeparator, StringComparison.OrdinalIgnoreCase)
            ? candidate
            : null;
    }
}
